### PR TITLE
Accept absolute URLs for h5p content

### PR DESCRIPTION
**Pull request by zbynek**
When an absolute URL of the content is specified, H5P standalone would still prepend https://host.tld making the URL of some resources invalid.

### CODE REVIEW

**Comment by zbynek** [comment]
@Jakeii do you plan to continue maintaining this project?

**Comment by sr258** [comment]
Check out if the HTML exporter of Lumi at https://next.lumi.education/ fits your needs. Maybe you don't need the standalone library then.

**Comment by zbynek** [comment]
@sr258 our current workflow is to allow users to upload .h5p files (using backend other than NodeJS), unzip them and use h5p-standalone to load the file. I tried https://github.com/Lumieducation/H5P-Nodejs-library , it runs nicely, but I'd like to avoid running JS on the server. Is a workflow like that possible with Lumi?

**Comment by Jakeii** [comment]
@zbynek I'll speak with our team and see if we can get more attention for this project, feel free to open a PR though!

**Comment by zbynek** [comment]
@Jakeii thanks! It would be great to also merge https://github.com/tunapanda/h5p-standalone/pull/54 -- I checked the fix and it indeed helped with the interactive book materials.

**Comment by sr258** [comment]
@zbynek Lumi is based on h5p-nodejs-library, so there's not difference here to the core library.

**Pull request merged**
