### PR TITLE
H5p version in path breaks it

### PR DESCRIPTION
**Pull request by Jakeii**
In the h5ps that Luka sent me for the course with reading section demo there seemed to be versions in the path.

atm it will probably just have work with the new version, till I can figure a way to be backwards compatible. https://github.com/h5p/h5p-editor-php-library/issues/18

### CODE REVIEW

**Comment by mgancarzdsi** [comment]
Hi Jake, FYI we're discussing your h5p-standalone tool on the H5P forums here: https://h5p.org/node/22947 and I'm really excited as it has the potential to allow us to directly embed h5p activites in a Lectora package or other places where we just want plain html presentation without requiring a CMS. 

I'm testing it now with our h5p files, and it works as long as I remove the version numbers on the end of the library files after extracting the h5p file into workspace. I am also testing this version you've tweaked to account for the version being in the path, but I am having some trouble with it, as it's missing the h5p-standalone-main.min.js file and when I manually create one by just copying h5p-standalone-main.js it gives me errors: 
"h5p-standalone-main.min.js:9592 Uncaught (in promise) TypeError: h5p.preloadedDependencies.findBy is not a function(…)(anonymous function) @ h5p-standalone-main.min.js:9592"

**Comment by mgancarzdsi** [comment]
Also, kudos on the work you've already done on this! It's really appreciated :+1:

**Comment by Jakeii** [comment]
Hi Mathew! Thanks for checking this out, I'm not sure how that findBy made it in there, it should be working now.

see [here](https://github.com/tunapanda/funzo-app/blob/master/app/pods/components/h5p-standalone/component.js) to see how we're using it if you're interested.

**Comment by Jakeii** [comment]
Hi @mgancarzdsi I think I found a solution, any chance that you have time to test?

**Comment by mgancarzdsi** [comment]
Sure @Jakeii, do you want me to just check out this branch or which code do you want me to test with?

**Comment by Jakeii** [comment]
Yes just check out this branch and make sure it works for you if you could,
if you have a projects with both kinds of paths (with/without versions)

**Comment by mgancarzdsi** [comment]
Hi Jakeii, confirmed working for h5p activities with versions in path, and also when I manually remove versions #'s from the folders. I don't have a genuine old activity to test with, but I think that's close enough.

**Comment by mgancarzdsi** [comment]
Great work on fixing it btw :+1:

**Comment by Jakeii** [comment]
Sweet thanks @mgancarzdsi !

**Pull request merged**
